:pig: 16.16.03.09.22

diff --git a/.github/workflows/build-image.yml b/.github/workflows/build-image.yml
--- a/.github/workflows/build-image.yml
+++ b/.github/workflows/build-image.yml
@@ -4,11 +4,15 @@ on:
   push:
     # Publish `main` as Docker `latest` image.
     branches:
-      - main_
+      - main
 
     # Publish `v1.2.3` tags as releases.
     tags:
       - v*
+
+concurrency:
+  group: ${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
 
 defaults:
   run:
@@ -25,12 +29,21 @@ jobs:
     permissions:
       packages: write
       contents: read
+    outputs:
+      build_id: ${{ steps.build_step.outputs.build_id }}
+      version: ${{ steps.push_step.outputs.version }}
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout
+        id: checkout_step
+        uses: actions/checkout@v2
 
       - name: Build image
-        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
+        id: build_step
+        run: |
+          docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
+          echo "Result of checkout_step was '${{ steps.checkout_step.outcome }}'"
+          echo "::set-output name=build_id::${GITHUB_RUN_ID}"
 
       - name: Login to Docker Hub
         uses: docker/login-action@v1
@@ -39,6 +52,7 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Push image
+        id: push_step
         run: |
           IMAGE_ID=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
 
@@ -54,3 +68,23 @@ jobs:
           echo VERSION=$VERSION
           docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
           docker push $IMAGE_ID:$VERSION
+
+          # Set version fo output2
+          echo "::set-output name=version::${VERSION}"
+
+          # Fake fails
+          if [[ $(($RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
+
+      - name: The job has failed
+        if: ${{ failure() }}
+        run: echo "The job has failed"
+
+  test_production_environment:
+    runs-on: ubuntu-latest
+    needs: [push]
+    environment: production
+    if: ${{ success() && github.event_name == 'push' }}
+
+    steps:
+      - run: echo ${{needs.push.outputs.build_id}}
+      - run: echo ${{ secrets.PRODUCTION_SECRET }}
